### ISSUE TITLE
Support node Selector for deployments & daemonset.

### ISSUE THREAD

**Issue by EnriqueHormilla** [soverenio/helm-charts#12]
Hi All, awesome helm!!!!

Could be great to have the possibility to use nodeSelector directly in values for:

- Daemonset for limit where soveren app doing tracking data.
- Deployments for grouping in specific node group as a core-apps

Something like this:
```
 {{- if .Values.deployments.nodeSelector.enabled }}
      nodeSelector:
        {{ toYaml .Values.deployments.nodeSelector.values | indent 1 }}
 {{- end }}
---
deployments:
  nodeSelector:
    enabled: true
    values:
      environment: ng-name
```
```
 {{- if .Values.daemonset.nodeSelector.enabled }}
      nodeSelector:
        {{ toYaml .Values.daemonset.nodeSelector.values | indent 1 }}
 {{- end }}
---
daemonset:
  nodeSelector:
    enabled: true
    values:
      environment: ng-name
```

**Comment by sdmironov** [comment]
Hello and thank you for your feedback (:

I've [added](https://github.com/soverenio/helm-charts/compare/soveren-agent-1.3.2...soveren-agent-1.3.3) the ability to configure a nodeSelector for each component in release 1.3.3 of the chart.

In example:

```
interceptor:
  nodeSelector:
    environment: ng-game

kafka:
  embedded:
    nodeSelector:
      environment: ng-game
```

**Comment by EnriqueHormilla** [comment]
Awesome support, thank very much @sdmironov  :)
